In [9]:
import os
os.chdir('/home/evgenii/ITMO')

import numpy as np
from drone_rescue_ai.environment.environment import Environment
from drone_rescue_ai.environment.environment_map import OBSTACLE_MAP, OBJECT_MAP, COLOR_MAP
from drone_rescue_ai.agent.agent import Agent

In [10]:
AREA_SIZE = (100, 100)
NUM_TARGETS = 3
NUM_OBSTACLES = 50
OBSERVATION_AREA = (9,9)
agent = Agent(area_size=AREA_SIZE, object_map=OBJECT_MAP, observation_area=OBSERVATION_AREA)

In [11]:
env = Environment(obstacles_map=OBSTACLE_MAP,
                color_map=COLOR_MAP,
                object_map=OBJECT_MAP,
                area_size=AREA_SIZE,
                num_targets=NUM_TARGETS,
                num_obstacles=NUM_OBSTACLES
                )

In [12]:
env.render_env('./rendered_env.jpg')

In [20]:
agent_position = (0,0)
for _ in range(150):
    action = agent.generate_action()
    print('Action: ', action)
    observation_area_of_agent = agent.get_observation_area()
    print('Agent observation area ', observation_area_of_agent)
    new_position, done, observation, obs_binary_mask = env.step(action, agent_position, observation_area_of_agent)

    agent_position = new_position

    print(f"New position : {new_position}, Done: {done}\n")
    # print(observation, '\n')
    agent.update_visited_map(observation, obs_binary_mask)
    print(agent.visited_map)

env.render_visited_map(agent.get_visited_map(), './visited_map.jpg')
env.render_observation(observation, './observation_exp1.jpg')

Action:  0
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  0
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  4
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  0
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  1
Agent observation area  (9, 9)
New position : (1, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  3
Agen

In [ ]:
agent_position = (0,0)
for _ in range(150):
    action = agent.generate_action()
    print('Action: ', action)
    observation_area_of_agent = agent.get_observation_area()
    print('Agent observation area ', observation_area_of_agent)
    new_position, done, observation, obs_binary_mask = env.step(action, agent_position, observation_area_of_agent)

    agent_position = new_position

    print(f"New position : {new_position}, Done: {done}\n")
    # print(observation, '\n')
    agent.update_visited_map(observation, obs_binary_mask)
    print(agent.visited_map)

env.render_visited_map(agent.get_visited_map(), './visited_map.jpg')
env.render_observation(observation, './observation_exp1.jpg')

Action:  0
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  0
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  4
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  0
Agent observation area  (9, 9)
New position : (0, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  1
Agent observation area  (9, 9)
New position : (1, 0), Done: True

[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
Action:  3
Agen